[2024-11-17T08:40:42.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-17T08:40:42.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_to_bq.dbt_run manual__2024-11-17T08:40:16.198645+00:00 [queued]>
[2024-11-17T08:40:42.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_to_bq.dbt_run manual__2024-11-17T08:40:16.198645+00:00 [queued]>
[2024-11-17T08:40:42.355+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-17T08:40:42.368+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-17 08:40:16.198645+00:00
[2024-11-17T08:40:42.373+0000] {standard_task_runner.py:63} INFO - Started process 1453 to run task
[2024-11-17T08:40:42.379+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'gcs_to_bq', 'dbt_run', 'manual__2024-11-17T08:40:16.198645+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpjrh5m6t0']
[2024-11-17T08:40:42.381+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask dbt_run
[2024-11-17T08:40:42.422+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_to_bq.dbt_run manual__2024-11-17T08:40:16.198645+00:00 [running]> on host portfolio.us-central1-c.c.golden-centaur-440309-a9.internal
[2024-11-17T08:40:42.489+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='gcs_to_bq' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T08:40:16.198645+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T08:40:16.198645+00:00'
[2024-11-17T08:40:42.490+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-17T08:40:42.503+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-17T08:40:42.504+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /path/to/my_dbt_project && dbt run --profiles-dir /path/to/.dbt']
[2024-11-17T08:40:42.513+0000] {subprocess.py:86} INFO - Output:
[2024-11-17T08:40:42.515+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /path/to/my_dbt_project: No such file or directory
[2024-11-17T08:40:42.515+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-17T08:40:42.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-17T08:40:42.527+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ghifariyadi_muhammad/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghifariyadi_muhammad/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghifariyadi_muhammad/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghifariyadi_muhammad/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-17T08:40:42.532+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gcs_to_bq, task_id=dbt_run, run_id=manual__2024-11-17T08:40:16.198645+00:00, execution_date=20241117T084016, start_date=20241117T084042, end_date=20241117T084042
[2024-11-17T08:40:42.545+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 1453)
[2024-11-17T08:40:42.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-17T08:40:42.605+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T08:40:42.606+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
